# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 0425100d-5f1d-4846-8207-93f8204275b3-capi-aws-check
  namespace: 0425100d-5f1d-4846-8207-93f8204275b3
spec:
  template:
    metadata:
      name: 0425100d-5f1d-4846-8207-93f8204275b3-capi-aws
    spec:
      serviceAccountName: 0425100d-5f1d-4846-8207-93f8204275b3-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 0425100d-5f1d-4846-8207-93f8204275b3
        - 0425100d-5f1d-4846-8207-93f8204275b3
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 0425100d-5f1d-4846-8207-93f8204275b3-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
