# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: 0425100d-5f1d-4846-8207-93f8204275b3
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    verbs:
    - get
    - list
    - update
    - watch
